version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  auth-service:
    build: ./auth-service
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - redis

  chat-service:
    build: ./chat-service
    ports:
      - "5002:5002"
    env_file:
      - .env
    depends_on:
      - redis

  socket-service:
    build: ./socket-service
    ports:
      - "5003:5003"
    env_file:
      - .env
    depends_on:
      - redis

  notification-service:
    build: ./notification-service
    ports:
      - "5004:5004"
    env_file:
      - .env
    depends_on:
      - redis

  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - auth-service
      - chat-service
      - socket-service
      - notification-service
